import{a as S,S as q,i as B}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const I="44324490-53902a9aa3f8bdbab535f7eec",P="https://pixabay.com/api/";async function m(o,t=1,i=15){const s=`${P}?key=${I}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${i}`,e=await S.get(s);if(e.status!==200)throw new Error("Failed to fetch images");return e.data}const h=document.querySelector(".gallery");function H(){h.innerHTML=""}function p(o){const t=o.map(({webformatURL:s,largeImageURL:e,tags:r,likes:a,views:v,comments:$,downloads:E})=>`
    <div class="photo-card">
      <a href="${e}" class="gallery__item">
        <img src="${s}" alt="${r}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b> ${a}</p>
        <p class="info-item"><b>Views</b> ${v}</p>
        <p class="info-item"><b>Comments</b> ${$}</p>
        <p class="info-item"><b>Downloads</b> ${E}</p>
      </div>
    </div>
  `).join("");h.insertAdjacentHTML("beforeend",t),new q(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const M=document.querySelector("#search-form"),O=document.querySelector("#search-form input"),_=document.querySelector(".gallery"),u=document.getElementById("load-more"),y=document.getElementById("loader");let c="",l=1;const d=15;let g=0;M.addEventListener("submit",async o=>{if(o.preventDefault(),c=O.value.trim(),c===""){n("Search query cannot be empty");return}l=1,H(),w(),b();try{const t=await m(c,l,d);if(g=t.totalHits,t.hits.length===0){n("Sorry, there are no images matching your search query. Please try again.");return}p(t.hits),t.totalHits>d&&L()}catch(t){n(t.message)}finally{f()}});u.addEventListener("click",async()=>{w(),b();try{await new Promise(t=>setTimeout(t,2e3));const o=await m(c,l,d);p(o.hits),l*d>=g?n("We're sorry, but you've reached the end of search results."):L(),x()}catch(o){n(o.message)}finally{f()}});function b(){y.classList.remove("hidden")}function f(){y.classList.add("hidden")}function n(o){f(),B.error({title:"Error",message:o,position:"topRight"})}function x(){const{height:o}=_.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}function L(){u.classList.remove("hidden")}function w(){u.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
