import{a as $,S as E,i as S}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();const q="44324490-53902a9aa3f8bdbab535f7eec",I="https://pixabay.com/api/";async function m(t,r=1,l=15){const s=`${I}?key=${q}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${l}`,e=await $.get(s);if(e.status!==200)throw new Error("Failed to fetch images");return e.data}const h=document.querySelector(".gallery");function P(){h.innerHTML=""}function p(t){const r=t.map(({webformatURL:s,largeImageURL:e,tags:o,likes:a,views:L,comments:v,downloads:w})=>`
    <div class="photo-card">
      <a href="${e}" class="gallery__item">
        <img src="${s}" alt="${o}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b> ${a}</p>
        <p class="info-item"><b>Views</b> ${L}</p>
        <p class="info-item"><b>Comments</b> ${v}</p>
        <p class="info-item"><b>Downloads</b> ${w}</p>
      </div>
    </div>
  `).join("");h.insertAdjacentHTML("beforeend",r),new E(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const B=document.querySelector("#search-form"),H=document.querySelector("#search-form input"),O=document.querySelector(".gallery"),i=document.getElementById("load-more"),y=document.getElementById("loader");let d="",n=1;const u=15;let g=0;B.addEventListener("submit",async t=>{if(t.preventDefault(),d=H.value.trim(),d===""){c("Search query cannot be empty");return}n=1,P(),i.classList.add("hidden"),b();try{const r=await m(d,n,u);if(g=r.totalHits,r.hits.length===0){c("Sorry, there are no images matching your search query. Please try again.");return}p(r.hits),r.totalHits>u&&i.classList.remove("hidden")}catch(r){c(r.message)}finally{f()}});i.addEventListener("click",async()=>{n+=1,i.classList.add("hidden"),b();try{const t=await m(d,n,u);setTimeout(()=>{p(t.hits),n*u>=g?c("We're sorry, but you've reached the end of search results."):i.classList.remove("hidden"),_()},2e3)}catch(t){c(t.message)}finally{f()}});function b(){y.classList.remove("hidden")}function f(){y.classList.add("hidden")}function c(t){f(),S.error({title:"Error",message:t,position:"topRight"})}function _(){const{height:t}=O.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
